groupName: acme.bwolf.me
logLevel: 6
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
image:
  repository: agaddy/cert-manager-webhook-gandi
  tag: 0.3.0
  pullPolicy: IfNotPresent
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 443
features:
  apiPriorityAndFairness: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
